# Generated by Django 5.1.4 on 2025-01-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
